alias scratch_c='vim $(printf "scratch-%s.c" $(date|awk -f file_name.awk))'
alias scratch_cpp='vim $(printf "scratch-%s.cpp" $(date|awk -f file_name.awk))'
alias scratch_rs='vim $(printf "scratch-%s.rs" $(date|awk -f file_name.awk))'
alias scratch_go='vim $(printf "scratch-%s.go" $(date|awk -f file_name.awk))'
alias scratch_py='vim $(printf "scratch-%s.py" $(date|awk -f file_name.awk))'
alias lf='konsole --fullscreen --hide-menubar -e lf 2>/dev/null'
alias vim=nvim
alias mv='mv -iv'
#alias cat=bat
alias tldr='tldr -t base16'
alias x=exit
alias chrome='google-chrome'
alias guile=guile3.0
